### PR TITLE
more content

### PR DESCRIPTION
**Pull request by fragmuffin**
@zignig 

I've started this off with a docker container to do a build.
I've found this to be an extremely convenient way to standardise
- running locally
- continuous integration
- deployment (which would be particularly neat for this project to publish to https://cqparts.github.io )

Once that's sorted, I'll merge over the content I was hard-coding from a clone of the `cqparts.github.io` repo.

### CODE REVIEW

**Comment by fragmuffin** [comment]
OK, so I think this is where I might need your help.
With the container as it is, I run it on a blank `sqlite` database: `data.db`, and I get the error:

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)
```

([full log](https://github.com/cqparts/cqparts_webapi/files/2659457/fail.log))

Can the script handle a completely blank database? or does it need some tables to exist first?

**Comment by fragmuffin** [comment]
oh!, forgot to mention.
When pulling local libs into the `env/python-libs` folder, it currently requires the branches in pull requests:
- zignig/cqparts_bucket#2
- cqparts/cqparts#131

**Comment by fragmuffin** [comment]
OK! now we're getting somewhere... I changed the sqlite database to `:memory:`.
(I'm sure I could fix whatever I did wrong before to make it persistent, but this is a start)

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: things [SQL: 'SELECT things.jsondata \nFROM things \nWHERE things.classname IS NULL AND things.prefix = ?'] [parameters: ('cache',)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

So it looks like the `sqlite` database requires (at least) a `things` table.
Do you have a `*.sql` file or something to populate an empty database?

**Comment by zignig** [comment]
> So it looks like the `sqlite` database requires (at least) a `things` table.
> Do you have a `*.sql` file or something to populate an empty database?

The sqlachemy should take care of this when if first creates the database. 

Nice work here , a docker would be help. I away for another week , but I should have some evening time across the Festivus break to buckle this down. 

I have some serious changes to the way the primary datastructure is built.

**Comment by fragmuffin** [comment]
Cool, I'll have a look into `sqlachemy` early this week.
I'm having fun with this.

**Comment by fragmuffin** [comment]
@zignig ok, the issue earlier was database persistence.
using the `:memory:` workaround was creating a new blank database each thread, although that doesn't completely make sense...

looks like I was missing a forward-slash in my original database uri; it's working with 4 forward-slashes `sqlite:////code/data.db`, which is a bit weird, 2 for `<protocol>://`, +1 to start at the root of the file-system, don't know why the 4th is needed.
Meh! not complaining, it's working :+1:

**Examples not rendering**
The `examples.html` isn't rendered (no HTML is generated). And no error occurs either.
If I remove the `for` loop, it works, so it's the original content (before this PR) that's not working in the contianer.
I'll look into that next, but I should mostly focus on the aesthetics of the additions I'm making (they're a bit ugly at the moment)

**Comment by fragmuffin** [comment]
@zignig I still can't see the examples, but it's not important for now.
If you can build the docker container, delete the database, and see examples when I can't, then something weird is going on... but I suspect your database is pre-populated where mine is not.

Scope: This PR is to add content to the landing page, I'm mostly just playing with CSS and `div` tags.

I was looking into file watch services today (which is now yesterday :roll_eyes:), and stumbled upon [facebook/watchman](https://facebook.github.io/watchman/).
It looks neat, but then this happened: facebook/watchman#660

Out of curiosity, I saw you were using [`CompileDaemon`](https://github.com/githubnemo/CompileDaemon) to do a similar task.
Rookie question: how did you install it? that small detail seems to be missing from the repo

**Comment by zignig** [comment]
I develop in golang as well. you need a working go install 

https://github.com/githubnemo/CompileDaemon

go install github.com/githubnemo/CompileDaemon/...

will a binary in $GOPATH/bin/CompileDaemon  , copy it into /usr/local/bin/

**Comment by fragmuffin** [comment]
I figured it was some go magic.
I'm still intrigued by watchman, it looks super configurable.

**Comment by zignig** [comment]
templated some of the pages, will look at doing the equivilent on the dump , should give us more style control over the cqparts website.

**Comment by fragmuffin** [comment]
Oh! It's merged, I was going to look more.i mm to this this weekend...
There's still plenty left undone.
I'll just continue with the same branch

**Comment by zignig** [comment]
All good,  keep working here. I wanted to merge because there is some other work I want to do from master.

**Pull request merged**
